/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inteligenciaartificial;

import inteligenciaartificial.controller.InteligenciaArtificialMaquina;
import inteligenciaartificial.controller.LetraController;
import inteligenciaartificial.controller.Letras;
import inteligenciaartificial.controller.PalavraController;
import inteligenciaartificial.controller.VariaveisGlobais;
import inteligenciaartificial.controller.Vida;
import inteligenciaartificial.model.Palavra;
import inteligenciaartificial.utils.DadosIniciais;
import inteligenciaartificial.utils.LetraRanking;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Soulcram
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private DadosIniciais dadosIniciais;
    private LetraController lc;
    private char[] letrasNaoEscolhidas = {'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Ç', 'Z', 'X', 'C', 'V', 'B', 'N', 'M'};
    private List<String> letrasJaEscolhidas = new ArrayList<>();


    private String palavra;

    private int inimigoDaVez;

//    char[] arrayPalavra;

    public JanelaPrincipal() {
        initComponents();
        new DadosIniciais();
        jButton1ActionPerformed(null);
        painelDeTeclas.setVisible(false);
        lc = new LetraController();
        VariaveisGlobais.vezJogador = true;
        InteligenciaArtificialMaquina iam = new InteligenciaArtificialMaquina();
        iam.setMsgInimigo(msgInimigo);
        iam.setPainelTeclas(painelDeTeclas);
        iam.setlPontos(lPontos);
        iam.setTamPalavra(tamPalavra);
        iam.setPalavraCompleta(palavraCompleta);
        iam.setlPalavraEscondida(lPalavraEscondida);
        iam.setVida(new Vida(vidaPlayer1, vidaPlayer2, vidaPlayer3, vidaPlayer4, vidaPlayer5, vidaPlayer6, vidaPlayer7, vidaPlayer8, vidaPlayer9, vidainimigo1, vidainimigo2, vidainimigo3, vidainimigo4, vidainimigo5, vidainimigo6, vidainimigo7, vidainimigo8, vidainimigo9));
        iam.setLetras(new Letras(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, ç));
        new Thread(iam).start();
        escolherPalavra();
        inicializarjogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPalavraEscondida = new javax.swing.JLabel();
        painelDeTeclas = new javax.swing.JPanel();
        q = new javax.swing.JButton();
        w = new javax.swing.JButton();
        r = new javax.swing.JButton();
        e = new javax.swing.JButton();
        i = new javax.swing.JButton();
        u = new javax.swing.JButton();
        t = new javax.swing.JButton();
        y = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        l = new javax.swing.JButton();
        ç = new javax.swing.JButton();
        k = new javax.swing.JButton();
        j = new javax.swing.JButton();
        h = new javax.swing.JButton();
        g = new javax.swing.JButton();
        f = new javax.swing.JButton();
        d = new javax.swing.JButton();
        s = new javax.swing.JButton();
        a = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        b = new javax.swing.JButton();
        v = new javax.swing.JButton();
        c = new javax.swing.JButton();
        x = new javax.swing.JButton();
        z = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msgInimigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        vidaPlayer1 = new javax.swing.JTextField();
        vidaPlayer2 = new javax.swing.JTextField();
        vidaPlayer3 = new javax.swing.JTextField();
        vidaPlayer4 = new javax.swing.JTextField();
        vidaPlayer5 = new javax.swing.JTextField();
        vidaPlayer6 = new javax.swing.JTextField();
        vidaPlayer7 = new javax.swing.JTextField();
        vidaPlayer8 = new javax.swing.JTextField();
        vidaPlayer9 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        vidainimigo1 = new javax.swing.JTextField();
        vidainimigo2 = new javax.swing.JTextField();
        vidainimigo3 = new javax.swing.JTextField();
        vidainimigo4 = new javax.swing.JTextField();
        vidainimigo5 = new javax.swing.JTextField();
        vidainimigo6 = new javax.swing.JTextField();
        vidainimigo7 = new javax.swing.JTextField();
        vidainimigo8 = new javax.swing.JTextField();
        vidainimigo9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lPontos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tamPalavra = new javax.swing.JLabel();
        palavraCompleta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha em Jogo da Forca");
        setBackground(new java.awt.Color(255, 255, 255));

        lPalavraEscondida.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lPalavraEscondida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPalavraEscondida.setText("Jogar");

        painelDeTeclas.setBackground(new java.awt.Color(51, 51, 51));

        q.setBackground(new java.awt.Color(0, 102, 153));
        q.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        q.setText("Q");
        q.setToolTipText("");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        w.setBackground(new java.awt.Color(0, 102, 153));
        w.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        w.setText("W");
        w.setToolTipText("");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        r.setBackground(new java.awt.Color(0, 102, 153));
        r.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        r.setText("R");
        r.setToolTipText("");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        e.setBackground(new java.awt.Color(0, 102, 153));
        e.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        e.setText("E");
        e.setToolTipText("");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        i.setBackground(new java.awt.Color(0, 102, 153));
        i.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        i.setText("I");
        i.setToolTipText("");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        u.setBackground(new java.awt.Color(0, 102, 153));
        u.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        u.setText("U");
        u.setToolTipText("");
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });

        t.setBackground(new java.awt.Color(0, 102, 153));
        t.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        t.setText("T");
        t.setToolTipText("");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });

        y.setBackground(new java.awt.Color(0, 102, 153));
        y.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        y.setText("Y");
        y.setToolTipText("");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        o.setBackground(new java.awt.Color(0, 102, 153));
        o.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        o.setText("O");
        o.setToolTipText("");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        p.setBackground(new java.awt.Color(0, 102, 153));
        p.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        p.setText("P");
        p.setToolTipText("");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        l.setBackground(new java.awt.Color(0, 102, 153));
        l.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        l.setText("L");
        l.setToolTipText("");
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        ç.setBackground(new java.awt.Color(0, 102, 153));
        ç.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ç.setText("Ç");
        ç.setToolTipText("");
        ç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çActionPerformed(evt);
            }
        });

        k.setBackground(new java.awt.Color(0, 102, 153));
        k.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        k.setText("K");
        k.setToolTipText("");
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        j.setBackground(new java.awt.Color(0, 102, 153));
        j.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j.setText("J");
        j.setToolTipText("");
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });

        h.setBackground(new java.awt.Color(0, 102, 153));
        h.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        h.setText("H");
        h.setToolTipText("");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        g.setBackground(new java.awt.Color(0, 102, 153));
        g.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        g.setText("G");
        g.setToolTipText("");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        f.setBackground(new java.awt.Color(0, 102, 153));
        f.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        f.setText("F");
        f.setToolTipText("");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        d.setBackground(new java.awt.Color(0, 102, 153));
        d.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        d.setText("D");
        d.setToolTipText("");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        s.setBackground(new java.awt.Color(0, 102, 153));
        s.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        s.setText("S");
        s.setToolTipText("");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        a.setBackground(new java.awt.Color(0, 102, 153));
        a.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a.setText("A");
        a.setToolTipText("");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        m.setBackground(new java.awt.Color(0, 102, 153));
        m.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        m.setText("M");
        m.setToolTipText("");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        n.setBackground(new java.awt.Color(0, 102, 153));
        n.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n.setText("N");
        n.setToolTipText("");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        b.setBackground(new java.awt.Color(0, 102, 153));
        b.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        b.setText("B");
        b.setToolTipText("");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        v.setBackground(new java.awt.Color(0, 102, 153));
        v.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        v.setText("V");
        v.setToolTipText("");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        c.setBackground(new java.awt.Color(0, 102, 153));
        c.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        c.setText("C");
        c.setToolTipText("");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        x.setBackground(new java.awt.Color(0, 102, 153));
        x.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        x.setText("X");
        x.setToolTipText("");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        z.setBackground(new java.awt.Color(0, 102, 153));
        z.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        z.setText("Z");
        z.setToolTipText("");
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeTeclasLayout = new javax.swing.GroupLayout(painelDeTeclas);
        painelDeTeclas.setLayout(painelDeTeclasLayout);
        painelDeTeclasLayout.setHorizontalGroup(
            painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeTeclasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeTeclasLayout.createSequentialGroup()
                        .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDeTeclasLayout.createSequentialGroup()
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ç, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeTeclasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        painelDeTeclasLayout.setVerticalGroup(
            painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeTeclasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ç, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDeTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inimigo5.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heroi1.png"))); // NOI18N

        msgInimigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        vidaPlayer1.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer2.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer3.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer4.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer5.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer6.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer7.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer8.setBackground(new java.awt.Color(255, 255, 0));

        vidaPlayer9.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vidaPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vidaPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        vidainimigo1.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo2.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo3.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo4.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo5.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo6.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo7.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo8.setBackground(new java.awt.Color(255, 255, 0));

        vidainimigo9.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vidainimigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidainimigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vidainimigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidainimigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pontos:");

        lPontos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lPontos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPontos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Iniciar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tamPalavra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tamPalavra.setText("TAMANHO DA PALAVRA");

        palavraCompleta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        palavraCompleta.setText("TAMANHO DA PALAVRA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(palavraCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(tamPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(lPalavraEscondida, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 141, Short.MAX_VALUE))
                            .addComponent(msgInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(painelDeTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tamPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palavraCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(msgInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lPalavraEscondida, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(painelDeTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        lPalavraEscondida.setText(verificarLetra('Q'));
        q.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();

    }//GEN-LAST:event_qActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        lPalavraEscondida.setText(verificarLetra('W'));
        w.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_wActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        lPalavraEscondida.setText(verificarLetra('E'));
        e.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_eActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicializarjogo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inicializarjogo(){
        escolherPalavra();
        reinicializarVidaPlayer();
        reinicializarVidaInimigo();
        lPalavraEscondida.setText(enconderPalavra());
        VariaveisGlobais.reiniciarVariaveis();
        deixarBotoesVisiveis();
        painelDeTeclas.setVisible(true);
        VariaveisGlobais.gameOver = false;
        msgInimigo.setText("É hora do Duelo!");
        inimigoDaVez = 1;
        novaImagemInimigo();
        
    }
    
    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        lPalavraEscondida.setText(verificarLetra('A'));
        a.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_aActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        lPalavraEscondida.setText(verificarLetra('R'));
        r.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_rActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        lPalavraEscondida.setText(verificarLetra('T'));
        t.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_tActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        lPalavraEscondida.setText(verificarLetra('Y'));
        y.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_yActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        lPalavraEscondida.setText(verificarLetra('U'));
        u.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_uActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        lPalavraEscondida.setText(verificarLetra('I'));
        i.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_iActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        lPalavraEscondida.setText(verificarLetra('O'));
        o.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_oActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
       lPalavraEscondida.setText(verificarLetra('P'));
        p.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_pActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        lPalavraEscondida.setText(verificarLetra('S'));
        s.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_sActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        lPalavraEscondida.setText(verificarLetra('D'));
        d.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_dActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        lPalavraEscondida.setText(verificarLetra('F'));
        f.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        lPalavraEscondida.setText(verificarLetra('G'));
        g.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        lPalavraEscondida.setText(verificarLetra('H'));
        h.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_hActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        lPalavraEscondida.setText(verificarLetra('J'));
        j.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        lPalavraEscondida.setText(verificarLetra('K'));
        k.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_kActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        lPalavraEscondida.setText(verificarLetra('L'));
        l.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_lActionPerformed

    private void çActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çActionPerformed
        lPalavraEscondida.setText(verificarLetra('Ç'));
        ç.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_çActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        lPalavraEscondida.setText(verificarLetra('Z'));
        z.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_zActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        lPalavraEscondida.setText(verificarLetra('X'));
        x.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_xActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        lPalavraEscondida.setText(verificarLetra('C'));
        c.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_cActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        lPalavraEscondida.setText(verificarLetra('V'));
        v.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_vActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        lPalavraEscondida.setText(verificarLetra('B'));
        b.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_bActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        lPalavraEscondida.setText(verificarLetra('N'));
        n.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_nActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        lPalavraEscondida.setText(verificarLetra('M'));
        m.setVisible(false);
        verificarGameOver();
        verificarVitoriaPalavra();
        verificarMorteInimigo();
    }//GEN-LAST:event_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    private void atualizarVidaPlayer() {
        if (VariaveisGlobais.qtdeVidaPlayer1 < 9) {
            vidaPlayer9.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 8) {
            vidaPlayer8.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 7) {
            vidaPlayer7.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 6) {
            vidaPlayer6.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 5) {
            vidaPlayer5.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 4) {
            vidaPlayer4.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 3) {
            vidaPlayer3.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 2) {
            vidaPlayer2.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer1 < 1) {
            vidaPlayer1.setBackground(Color.red);
        }

    }

    private void reinicializarVidaPlayer() {
        vidaPlayer1.setBackground(Color.yellow);
        vidaPlayer2.setBackground(Color.yellow);
        vidaPlayer3.setBackground(Color.yellow);
        vidaPlayer4.setBackground(Color.yellow);
        vidaPlayer5.setBackground(Color.yellow);
        vidaPlayer6.setBackground(Color.yellow);
        vidaPlayer7.setBackground(Color.yellow);
        vidaPlayer8.setBackground(Color.yellow);
        vidaPlayer9.setBackground(Color.yellow);
        VariaveisGlobais.qtdeVidaPlayer1 = 9;
    }

    private void atualizarVidainimigo() {
        if (VariaveisGlobais.qtdeVidaPlayer2 < 9) {
            vidainimigo9.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 8) {
            vidainimigo8.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 7) {
            vidainimigo7.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 6) {
            vidainimigo6.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 5) {
            vidainimigo5.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 4) {
            vidainimigo4.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 3) {
            vidainimigo3.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 2) {
            vidainimigo2.setBackground(Color.red);
        }
        if (VariaveisGlobais.qtdeVidaPlayer2 < 1) {
            vidainimigo1.setBackground(Color.red);
        }

    }

    private void reinicializarVidaInimigo() {
        vidainimigo1.setBackground(Color.yellow);
        vidainimigo2.setBackground(Color.yellow);
        vidainimigo3.setBackground(Color.yellow);
        vidainimigo4.setBackground(Color.yellow);
        vidainimigo5.setBackground(Color.yellow);
        vidainimigo6.setBackground(Color.yellow);
        vidainimigo7.setBackground(Color.yellow);
        vidainimigo8.setBackground(Color.yellow);
        vidainimigo9.setBackground(Color.yellow);
        VariaveisGlobais.qtdeVidaPlayer2 = 9;
    }

    private String verificarLetra(char letra) {
        boolean controle = false;
        String x = "";
        int y = 0;
        boolean hasAcerto = false;
        VariaveisGlobais.letrasJaEscolhidas.add(String.valueOf(letra));
        VariaveisGlobais.arrayPalavra = VariaveisGlobais.p1.getPalavra().toCharArray();

        for (char c : VariaveisGlobais.arrayPalavra) {
            if (c == letra) {
                hasAcerto = true;
                VariaveisGlobais.palavraEscondida[y] = c;
                controle = true;

                //playSoundClick();
                VariaveisGlobais.pontos += 100;
                

            } else if (c == VariaveisGlobais.palavraEscondida[y]) {
            } else {

                VariaveisGlobais.palavraEscondida[y] = '_';

            }

            y++;

        }

        for (char c : VariaveisGlobais.palavraEscondida) {
            if (c == '_') {
                x += "_ ";
            } else {
                x += c;
            }
        }

        if (hasAcerto) {
            LetraRanking lr = lc.consultarByLetra(String.valueOf(letra));
            lr.setCerto(lr.getCerto() + 1);
            hitPlayer2();
            lc.alterarLetra(lr);
            //layoutPlayer1.setBackgroundColor(Color.GREEN);
            //layoutPlayer2.setBackgroundColor(Color.RED);

        } else {
            LetraRanking lr = lc.consultarByLetra(String.valueOf(letra));
            lr.setErrado(lr.getErrado() + 1);
            //layoutPlayer1.setBackgroundColor(Color.RED);
            //layoutPlayer2.setBackgroundColor(Color.GREEN);
            lc.alterarLetra(lr);
            VariaveisGlobais.vezJogador = !VariaveisGlobais.vezJogador;
            //vezComputador();
        }

        removerLetraEscolhida(letra);
        //deixarBotoesInvisiveis();

        //pontosTextView.setText(String.valueOf(pontos));
        return x;

    }

    private void removerLetraEscolhida(char letra) {
        int x = 0;
        for (char c : letrasNaoEscolhidas) {
            if (c == letra) {

                letrasJaEscolhidas.add(String.valueOf(c));
                letrasNaoEscolhidas[x] = '0';
            }
            x++;
        }

    }

    private void verificarGameOver() {
        if (VariaveisGlobais.qtdeVidaPlayer1 <= 0) {

            VariaveisGlobais.gameOver = true;

        }
    }

    private void verificarVitoriaPalavra() {
        //char [] teste = pe.getText().toString().toCharArray();
        int x = 0;
        String p = "";
        for (char c : VariaveisGlobais.palavraEscondida) {
            if (c == '_') {
                x++;
            }
            else{
                p += String.valueOf(c);
            }
        }
        if (x <= 0) {
            VariaveisGlobais.palavraCorreta = p;
            sleep(2000);
            gerarNovaPalavra();
        }
    }
    
    private void sleep(int tempo) {
        try {
            Thread.sleep(tempo);
        } catch (InterruptedException e1) {
            e1.printStackTrace();
        }
    }

    private void gerarNovaPalavra() {
        escolherPalavra();
        lPalavraEscondida.setText(enconderPalavra());
        deixarBotoesVisiveis();
        char[] novoletrasNaoEscolhidas = {'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Ç', 'Z', 'X', 'C', 'V', 'B', 'N', 'M'};
        VariaveisGlobais.letrasNaoEscolhidas = novoletrasNaoEscolhidas;
        VariaveisGlobais.letrasJaEscolhidas = new ArrayList<>();
    }

    public String enconderPalavra() {
        String x = "";
        VariaveisGlobais.arrayPalavra = VariaveisGlobais.p1.getPalavra().toCharArray();
        for (char c : VariaveisGlobais.arrayPalavra) {
            x += "_ ";
        }

        VariaveisGlobais.palavraEscondida = new char[VariaveisGlobais.arrayPalavra.length];
        VariaveisGlobais.palavraCorreta = "";
        return x;
    }

    public void escolherPalavra() {
        PalavraController pc = new PalavraController();

        Random rand = new Random();
        int n = rand.nextInt(pc.qtdeItensCadastrados());

        VariaveisGlobais.p1 = pc.consultarByID(n);

    }

    private void verificarMorteInimigo() {
        if (VariaveisGlobais.qtdeVidaPlayer2 <= 0) {
            inimigoDaVez++;
            novoInimigo();
            gerarNovaPalavra();

        }
    }

    private void hitPlayer2() {
        VariaveisGlobais.qtdeVidaPlayer2 -= 1;

    }

    private void novoInimigo() {
        VariaveisGlobais.qtdeVidaPlayer2 = 9;
        novaImagemInimigo();
        VariaveisGlobais.qtdeVidaPlayer1 += 1;
        VariaveisGlobais.novoInimigo = true;

    }

    private void novaImagemInimigo() {
        if (inimigoDaVez > 6) {
            inimigoDaVez = 1;
        }
       
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inimigo"+inimigoDaVez+".png")));

    }

    private void deixarBotoesVisiveis() {
        q.setVisible(true);
        w.setVisible(true);
        e.setVisible(true);
        r.setVisible(true);
        t.setVisible(true);
        y.setVisible(true);
        u.setVisible(true);
        i.setVisible(true);
        o.setVisible(true);
        p.setVisible(true);
        a.setVisible(true);
        s.setVisible(true);
        d.setVisible(true);
        f.setVisible(true);
        g.setVisible(true);
        h.setVisible(true);
        j.setVisible(true);
        k.setVisible(true);
        l.setVisible(true);
        ç.setVisible(true);
        z.setVisible(true);
        x.setVisible(true);
        c.setVisible(true);
        v.setVisible(true);
        b.setVisible(true);
        n.setVisible(true);
        m.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JLabel lPalavraEscondida;
    private javax.swing.JLabel lPontos;
    private javax.swing.JButton m;
    private javax.swing.JLabel msgInimigo;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JPanel painelDeTeclas;
    private javax.swing.JLabel palavraCompleta;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JLabel tamPalavra;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JTextField vidaPlayer1;
    private javax.swing.JTextField vidaPlayer2;
    private javax.swing.JTextField vidaPlayer3;
    private javax.swing.JTextField vidaPlayer4;
    private javax.swing.JTextField vidaPlayer5;
    private javax.swing.JTextField vidaPlayer6;
    private javax.swing.JTextField vidaPlayer7;
    private javax.swing.JTextField vidaPlayer8;
    private javax.swing.JTextField vidaPlayer9;
    private javax.swing.JTextField vidainimigo1;
    private javax.swing.JTextField vidainimigo2;
    private javax.swing.JTextField vidainimigo3;
    private javax.swing.JTextField vidainimigo4;
    private javax.swing.JTextField vidainimigo5;
    private javax.swing.JTextField vidainimigo6;
    private javax.swing.JTextField vidainimigo7;
    private javax.swing.JTextField vidainimigo8;
    private javax.swing.JTextField vidainimigo9;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    private javax.swing.JButton ç;
    // End of variables declaration//GEN-END:variables
}
